/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as CancellationRouteImport } from './routes/cancellation'
import { Route as CollectionRouteImport } from './routes/collection'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CookiePolicyRouteImport } from './routes/cookie-policy'
import { Route as DisclaimerRouteImport } from './routes/disclaimer'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as LabReportsRouteImport } from './routes/lab-reports'
import { Route as LabTestingRouteImport } from './routes/lab-testing'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as QualityRouteImport } from './routes/quality'
import { Route as ResearchRouteImport } from './routes/research'
import { Route as ReturnsRouteImport } from './routes/returns'
import { Route as ShippingRouteImport } from './routes/shipping'
import { Route as SitemapRouteImport } from './routes/sitemap'
import { Route as SitemapProductsDotxmlRouteImport } from './routes/sitemap-products[.]xml'
import { Route as StandardsRouteImport } from './routes/standards'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ProductHandleRouteImport } from './routes/product.$handle'
import { Route as ResearchSlugRouteImport } from './routes/research_.$slug'
import { Route as ApiPublicNewsletterSubscribeRouteImport } from './routes/api/public/newsletter-subscribe'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const CancellationRoute = CancellationRouteImport.update({
  id: '/cancellation',
  path: '/cancellation',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionRoute = CollectionRouteImport.update({
  id: '/collection',
  path: '/collection',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiePolicyRoute = CookiePolicyRouteImport.update({
  id: '/cookie-policy',
  path: '/cookie-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const DisclaimerRoute = DisclaimerRouteImport.update({
  id: '/disclaimer',
  path: '/disclaimer',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const LabReportsRoute = LabReportsRouteImport.update({
  id: '/lab-reports',
  path: '/lab-reports',
  getParentRoute: () => rootRouteImport,
} as any)
const LabTestingRoute = LabTestingRouteImport.update({
  id: '/lab-testing',
  path: '/lab-testing',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const QualityRoute = QualityRouteImport.update({
  id: '/quality',
  path: '/quality',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchRoute = ResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => rootRouteImport,
} as any)
const ReturnsRoute = ReturnsRouteImport.update({
  id: '/returns',
  path: '/returns',
  getParentRoute: () => rootRouteImport,
} as any)
const ShippingRoute = ShippingRouteImport.update({
  id: '/shipping',
  path: '/shipping',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapRoute = SitemapRouteImport.update({
  id: '/sitemap',
  path: '/sitemap',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapProductsDotxmlRoute = SitemapProductsDotxmlRouteImport.update({
  id: '/sitemap-products.xml',
  path: '/sitemap-products.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const StandardsRoute = StandardsRouteImport.update({
  id: '/standards',
  path: '/standards',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductHandleRoute = ProductHandleRouteImport.update({
  id: '/product/$handle',
  path: '/product/$handle',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchSlugRoute = ResearchSlugRouteImport.update({
  id: '/research_/$slug',
  path: '/research/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicNewsletterSubscribeRoute =
  ApiPublicNewsletterSubscribeRouteImport.update({
    id: '/api/public/newsletter-subscribe',
    path: '/api/public/newsletter-subscribe',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cancellation': typeof CancellationRoute
  '/collection': typeof CollectionRoute
  '/contact': typeof ContactRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/disclaimer': typeof DisclaimerRoute
  '/faq': typeof FaqRoute
  '/lab-reports': typeof LabReportsRoute
  '/lab-testing': typeof LabTestingRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/quality': typeof QualityRoute
  '/research': typeof ResearchRoute
  '/returns': typeof ReturnsRoute
  '/shipping': typeof ShippingRoute
  '/sitemap': typeof SitemapRoute
  '/sitemap-products.xml': typeof SitemapProductsDotxmlRoute
  '/standards': typeof StandardsRoute
  '/terms': typeof TermsRoute
  '/product/$handle': typeof ProductHandleRoute
  '/research/$slug': typeof ResearchSlugRoute
  '/api/public/newsletter-subscribe': typeof ApiPublicNewsletterSubscribeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cancellation': typeof CancellationRoute
  '/collection': typeof CollectionRoute
  '/contact': typeof ContactRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/disclaimer': typeof DisclaimerRoute
  '/faq': typeof FaqRoute
  '/lab-reports': typeof LabReportsRoute
  '/lab-testing': typeof LabTestingRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/quality': typeof QualityRoute
  '/research': typeof ResearchRoute
  '/returns': typeof ReturnsRoute
  '/shipping': typeof ShippingRoute
  '/sitemap': typeof SitemapRoute
  '/sitemap-products.xml': typeof SitemapProductsDotxmlRoute
  '/standards': typeof StandardsRoute
  '/terms': typeof TermsRoute
  '/product/$handle': typeof ProductHandleRoute
  '/research/$slug': typeof ResearchSlugRoute
  '/api/public/newsletter-subscribe': typeof ApiPublicNewsletterSubscribeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cancellation': typeof CancellationRoute
  '/collection': typeof CollectionRoute
  '/contact': typeof ContactRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/disclaimer': typeof DisclaimerRoute
  '/faq': typeof FaqRoute
  '/lab-reports': typeof LabReportsRoute
  '/lab-testing': typeof LabTestingRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/quality': typeof QualityRoute
  '/research': typeof ResearchRoute
  '/returns': typeof ReturnsRoute
  '/shipping': typeof ShippingRoute
  '/sitemap': typeof SitemapRoute
  '/sitemap-products.xml': typeof SitemapProductsDotxmlRoute
  '/standards': typeof StandardsRoute
  '/terms': typeof TermsRoute
  '/product/$handle': typeof ProductHandleRoute
  '/research_/$slug': typeof ResearchSlugRoute
  '/api/public/newsletter-subscribe': typeof ApiPublicNewsletterSubscribeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/cancellation'
    | '/collection'
    | '/contact'
    | '/cookie-policy'
    | '/disclaimer'
    | '/faq'
    | '/lab-reports'
    | '/lab-testing'
    | '/privacy-policy'
    | '/quality'
    | '/research'
    | '/returns'
    | '/shipping'
    | '/sitemap'
    | '/sitemap-products.xml'
    | '/standards'
    | '/terms'
    | '/product/$handle'
    | '/research/$slug'
    | '/api/public/newsletter-subscribe'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/cancellation'
    | '/collection'
    | '/contact'
    | '/cookie-policy'
    | '/disclaimer'
    | '/faq'
    | '/lab-reports'
    | '/lab-testing'
    | '/privacy-policy'
    | '/quality'
    | '/research'
    | '/returns'
    | '/shipping'
    | '/sitemap'
    | '/sitemap-products.xml'
    | '/standards'
    | '/terms'
    | '/product/$handle'
    | '/research/$slug'
    | '/api/public/newsletter-subscribe'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/cancellation'
    | '/collection'
    | '/contact'
    | '/cookie-policy'
    | '/disclaimer'
    | '/faq'
    | '/lab-reports'
    | '/lab-testing'
    | '/privacy-policy'
    | '/quality'
    | '/research'
    | '/returns'
    | '/shipping'
    | '/sitemap'
    | '/sitemap-products.xml'
    | '/standards'
    | '/terms'
    | '/product/$handle'
    | '/research_/$slug'
    | '/api/public/newsletter-subscribe'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CancellationRoute: typeof CancellationRoute
  CollectionRoute: typeof CollectionRoute
  ContactRoute: typeof ContactRoute
  CookiePolicyRoute: typeof CookiePolicyRoute
  DisclaimerRoute: typeof DisclaimerRoute
  FaqRoute: typeof FaqRoute
  LabReportsRoute: typeof LabReportsRoute
  LabTestingRoute: typeof LabTestingRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  QualityRoute: typeof QualityRoute
  ResearchRoute: typeof ResearchRoute
  ReturnsRoute: typeof ReturnsRoute
  ShippingRoute: typeof ShippingRoute
  SitemapRoute: typeof SitemapRoute
  SitemapProductsDotxmlRoute: typeof SitemapProductsDotxmlRoute
  StandardsRoute: typeof StandardsRoute
  TermsRoute: typeof TermsRoute
  ProductHandleRoute: typeof ProductHandleRoute
  ResearchSlugRoute: typeof ResearchSlugRoute
  ApiPublicNewsletterSubscribeRoute: typeof ApiPublicNewsletterSubscribeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cancellation': {
      id: '/cancellation'
      path: '/cancellation'
      fullPath: '/cancellation'
      preLoaderRoute: typeof CancellationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collection': {
      id: '/collection'
      path: '/collection'
      fullPath: '/collection'
      preLoaderRoute: typeof CollectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookie-policy': {
      id: '/cookie-policy'
      path: '/cookie-policy'
      fullPath: '/cookie-policy'
      preLoaderRoute: typeof CookiePolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disclaimer': {
      id: '/disclaimer'
      path: '/disclaimer'
      fullPath: '/disclaimer'
      preLoaderRoute: typeof DisclaimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab-reports': {
      id: '/lab-reports'
      path: '/lab-reports'
      fullPath: '/lab-reports'
      preLoaderRoute: typeof LabReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab-testing': {
      id: '/lab-testing'
      path: '/lab-testing'
      fullPath: '/lab-testing'
      preLoaderRoute: typeof LabTestingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quality': {
      id: '/quality'
      path: '/quality'
      fullPath: '/quality'
      preLoaderRoute: typeof QualityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research': {
      id: '/research'
      path: '/research'
      fullPath: '/research'
      preLoaderRoute: typeof ResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/returns': {
      id: '/returns'
      path: '/returns'
      fullPath: '/returns'
      preLoaderRoute: typeof ReturnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shipping': {
      id: '/shipping'
      path: '/shipping'
      fullPath: '/shipping'
      preLoaderRoute: typeof ShippingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap': {
      id: '/sitemap'
      path: '/sitemap'
      fullPath: '/sitemap'
      preLoaderRoute: typeof SitemapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap-products.xml': {
      id: '/sitemap-products.xml'
      path: '/sitemap-products.xml'
      fullPath: '/sitemap-products.xml'
      preLoaderRoute: typeof SitemapProductsDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/standards': {
      id: '/standards'
      path: '/standards'
      fullPath: '/standards'
      preLoaderRoute: typeof StandardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$handle': {
      id: '/product/$handle'
      path: '/product/$handle'
      fullPath: '/product/$handle'
      preLoaderRoute: typeof ProductHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research_/$slug': {
      id: '/research_/$slug'
      path: '/research/$slug'
      fullPath: '/research/$slug'
      preLoaderRoute: typeof ResearchSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/newsletter-subscribe': {
      id: '/api/public/newsletter-subscribe'
      path: '/api/public/newsletter-subscribe'
      fullPath: '/api/public/newsletter-subscribe'
      preLoaderRoute: typeof ApiPublicNewsletterSubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CancellationRoute: CancellationRoute,
  CollectionRoute: CollectionRoute,
  ContactRoute: ContactRoute,
  CookiePolicyRoute: CookiePolicyRoute,
  DisclaimerRoute: DisclaimerRoute,
  FaqRoute: FaqRoute,
  LabReportsRoute: LabReportsRoute,
  LabTestingRoute: LabTestingRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  QualityRoute: QualityRoute,
  ResearchRoute: ResearchRoute,
  ReturnsRoute: ReturnsRoute,
  ShippingRoute: ShippingRoute,
  SitemapRoute: SitemapRoute,
  SitemapProductsDotxmlRoute: SitemapProductsDotxmlRoute,
  StandardsRoute: StandardsRoute,
  TermsRoute: TermsRoute,
  ProductHandleRoute: ProductHandleRoute,
  ResearchSlugRoute: ResearchSlugRoute,
  ApiPublicNewsletterSubscribeRoute: ApiPublicNewsletterSubscribeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
